
import { AssessmentType, Recommendation } from './types';

export const UI_TRANSLATIONS = {
  ar: {
    dashboard: 'الرئيسية',
    patients: 'المرضى',
    intake: 'المقابلة الإكلينيكية',
    observation: 'الملاحظة السلوكية',
    assessments: 'المقاييس النفسية',
    dsm: 'مدقق DSM-5',
    recommendations: 'بنك التوصيات',
    reports: 'صانع التقارير',
    final_report: 'التقرير الشامل',
    calendar: 'المواعيد',
    billing: 'الباقات والرصيد',
    settings: 'الإعدادات',
    sessions: 'تقرير الجلسات', // Added
    active_patients: 'المرضى النشطون',
    issued_reports: 'التقارير الصادرة',
    credits: 'الرصيد المتاح',
    alerts: 'تنبيهات حرجة',
    lang_switch: 'English Interface',
    save: 'حفظ',
    next: 'التالي',
    back: 'السابق',
    finish: 'إنهاء وحفظ',
    select_patient: '-- اختر مريضاً --',
    clinical_session_active: 'جلسة إكلينيكية نشطة',
    chief_complaint: 'الشكوى الرئيسية',
    history_presenting_illness: 'تاريخ المرض الحالي (HPI)',
    symptom_phenomenology: 'مصفوفة الأعراض الظاهراتية',
    past_medical_history: 'التاريخ الطبي النفسي السابق',
    family_genetic_history: 'التاريخ العائلي والوراثي',
    developmental_history: 'التاريخ النمائي',
    occupational_functioning: 'الأداء الوظيفي والمهني',
    clinical_formulation: 'الصياغة الإكلينيكية والتشخيص',
    mental_status_exam: 'فحص الحالة العقلية (MSE)',
    informant: 'مصدر المعلومات',
    nature_presentation: 'طبيعة الزيارة',
    onset: 'بداية الحالة',
    course: 'مسار الحالة',
    mood_symptoms: 'أعراض وجدانية',
    cognitive_symptoms: 'أعراض معرفية',
    psychotic_symptoms: 'أعراض ذهانية',
    social_history: 'التاريخ الاجتماعي',
    edu_occupational: 'الأداء الأكاديمي/الوظيفي',
    provisional_dx: 'التشخيص المبدئي',
    plan: 'خطة التدخل',
    clinical_notes: 'ملاحظات إكلينيكية',
    reset_analysis: 'إعادة التصفير',
    met: 'مطابق',
    not_met: 'قيد المراجعة',
    psychometrics_unit: 'وحدة القياس النفسي',
    manual_entry: 'واجهة إدخال الدرجات',
    select_test: 'اختر المقياس',
    score_val: 'الدرجة',
    score_class: 'التصنيف',
    ai_analysis: 'التحليل الذكي (AI)',
    generate_ai: 'توليد التحليل',
    finalize_assessment: 'اعتماد وحفظ المقياس',
    specialist_notes: 'ملاحظات الأخصائي',
    enter_observations: 'سجل ملاحظاتك أثناء التطبيق...',
    // Session Recorder
    sr_title: 'سجل الجلسات العلاجية',
    sr_subtitle: 'توثيق إكلينيكي بنظام SOAP Notes',
    sr_new_note: 'جلسة جديدة',
    sr_history: 'سجل الجلسات',
    sr_date: 'تاريخ الجلسة',
    sr_duration: 'المدة (دقيقة)',
    sr_session_num: 'رقم الجلسة',
    sr_subjective: 'المعلومات الذاتية (Subjective)',
    sr_subjective_ph: 'ما قاله المريض، الشكوى الحالية، التحديثات منذ آخر جلسة...',
    sr_objective: 'الملاحظة الموضوعية (Objective)',
    sr_objective_ph: 'المظهر، السلوك، الانفعال، الحالة العقلية أثناء الجلسة...',
    sr_assessment: 'التقييم والتحليل (Assessment)',
    sr_assessment_ph: 'تحليل المعالج للتقدم، الاستبصار، التغيرات الإكلينيكية...',
    sr_plan: 'الخطة والواجبات (Plan)',
    sr_plan_ph: 'الواجب المنزلي، التدخلات القادمة، موعد الجلسة التالية...',
    sr_interventions: 'التدخلات المستخدمة',
    sr_mood_rating: 'تقييم المزاج (1-10)',
    sr_risk: 'تقييم الخطر',
    sr_risk_low: 'منخفض',
    sr_risk_med: 'متوسط',
    sr_risk_high: 'مرتفع',
    sr_save_btn: 'حفظ وتوثيق الجلسة',
    sr_no_history: 'لا توجد جلسات مسجلة لهذا المريض.',
    sr_view_details: 'عرض التفاصيل',
    // Report Maker Specific
    rm_title: 'صانع التقارير الذكي',
    rm_subtitle: 'Clinical Report Composer',
    rm_import_btn: 'استيراد البيانات تلقائياً',
    rm_preview_btn: 'معاينة وطباعة',
    rm_select_patient: 'اختر ملف المريض',
    rm_tab_context: 'البيانات والسوابق',
    rm_tab_behavior: 'الملاحظة السلوكية',
    rm_tab_tests: 'نتائج الاختبارات',
    rm_tab_diagnosis: 'الصياغة التشخيصية',
    rm_tab_plan: 'التوصيات والخطة',
    rm_ph_context: 'أدخل سبب الزيارة، تاريخ المرض الحالي، والتاريخ الطبي السابق...',
    rm_ph_behavior: 'صف المظهر، التواصل، المزاج، والسلوك العام للمفحوص...',
    rm_ph_tests_interp: 'اكتب تفسير الدرجات هنا...',
    rm_ph_diagnosis: 'الخلاصة: بناءً على ما سبق، فإن المريض يعاني من...',
    rm_ph_rec_add: 'اكتب توصية جديدة واضغط Enter...',
    rm_add_test_btn: 'إضافة اختبار يدوي',
    rm_no_tests: 'لا توجد نتائج اختبارات. اضغط "استيراد تلقائي" أو أضف يدوياً.',
    rm_no_recs: 'لم يتم إضافة أي توصيات بعد.',
    // Report Print View
    print_title: 'التقرير النفسي الإكلينيكي',
    print_subtitle: 'Confidential Clinical Psychological Report',
    print_ref: 'Ref',
    print_date: 'Date',
    print_pt_name: 'اسم المريض',
    print_pt_dob: 'تاريخ الميلاد',
    print_pt_gender: 'الجنس',
    print_pt_ref: 'جهة التحويل',
    print_sec_context: 'سبب الإحالة وتاريخ الحالة',
    print_sec_behavior: 'الملاحظات السلوكية (MSE)',
    print_sec_tests: 'نتائج الاختبارات والمقاييس',
    print_sec_diagnosis: 'الملخص والصياغة الإكلينيكية',
    print_sec_plan: 'التوصيات والخطة العلاجية',
    print_footer_sig: 'التوقيع / Signature',
    print_footer_spec: 'الأخصائي النفسي المعالج',
    print_footer_stamp: 'ختم العيادة',
    print_back: 'العودة للمحرر',
    print_save: 'حفظ التقرير',
    print_action: 'طباعة / تصدير PDF',
    // Recommendations Engine
    re_title: 'بنك التوصيات الذكي',
    re_subtitle: 'Clinical Intervention Matrix',
    re_add_btn: 'إضافة توصية جديدة',
    re_filter_dx: 'تصفية حسب التشخيص',
    re_search_ph: 'ابحث في بنك التوصيات...',
    re_cat_all: 'الكل',
    re_cat_school: 'المدرسة',
    re_cat_home: 'المنزل',
    re_selected: 'تم تحديد توصيات',
    re_copy_bulk: 'نسخ المجموعة',
    re_cancel: 'إلغاء التحديد',
    re_type_acc: 'تسهيلات',
    re_type_mod: 'تعديلات',
    re_modal_title: 'إضافة توصية مخصصة',
    re_modal_text: 'نص التوصية',
    re_modal_cat: 'البيئة',
    re_modal_type: 'النوع',
    re_modal_tags: 'الكلمات الدلالية',
    re_modal_save: 'حفظ في بنك التوصيات',
    // Patient Manager
    pm_search_placeholder: 'البحث عن مريض بالاسم أو الهاتف...',
    pm_add_btn: 'إضافة مريض',
    pm_full_record: 'السجل الكامل',
    pm_edit_title: 'تعديل بيانات المريض',
    pm_new_title: 'إضافة مريض جديد',
    pm_label_name: 'الاسم بالكامل',
    pm_ph_name: 'أدخل اسم المريض الرباعي',
    pm_label_dob: 'تاريخ الميلاد',
    pm_calc_age: 'العمر التفصيلي',
    pm_label_phone: 'رقم الجوال',
    pm_label_gender: 'الجنس',
    pm_gender_male: 'ذكر',
    pm_gender_female: 'أنثى',
    pm_label_notes: 'ملاحظات إضافية (اختياري)',
    pm_ph_notes: 'تاريخ مرضي مختصر أو ملاحظات أولية...',
    pm_cancel: 'إلغاء',
    pm_save: 'حفظ البيانات',
    pm_err_required: 'البيانات الأساسية مطلوبة',
    // Final Report Manager
    fr_title: 'محرك صياغة التقارير النهائية',
    fr_select_label: 'حدد ملف المريض لاستيراد البيانات',
    fr_select_ph: '-- اختر المريض للمراجعة الإكلينيكية --',
    fr_readiness: 'جاهزية البيانات للتقرير النهائي',
    fr_intake: 'المقابلة (Intake)',
    fr_mse: 'الملاحظة (MSE)',
    fr_tests: 'المقاييس',
    fr_dx_plan: 'التشخيص والتوصيات',
    fr_btn_generate: 'صياغة ومعاينة التقرير النهائي الشامل',
    fr_err_missing: 'لا يمكن إنشاء التقرير بدون بيانات "المقابلة الإكلينيكية" الأساسية.',
    fr_optional: 'اختياري',
    fr_none: 'لا يوجد',
    // Final Report Preview
    rp_header_title: 'تصدير التقرير النهائي',
    rp_edit: 'تعديل التقرير',
    rp_save: 'حفظ التعديلات',
    rp_print: 'طباعة التقرير',
    rp_sec_1: 'أولاً: بيانات الحالة والشكوى',
    rp_sec_2: 'ثانياً: نتائج التقييمات السيكومترية',
    rp_sec_3: 'ثالثاً: التشخيص الإكلينيكي النهائي',
    rp_sec_4: 'رابعاً: التوصيات التدخلية',
    rp_tbl_domain: 'المجال / الوحدة',
    rp_tbl_score: 'الدرجة',
    rp_tbl_class: 'التفسير الإحصائي',
    rp_sig_spec: 'توقيع الأخصائي المعالج',
    rp_sig_stamp: 'ختم العيادة الرسمي',
    rp_add_rec: 'إضافة توصية أخرى',
    // Calendar
    cal_title: 'الأجندة اليومية',
    cal_subtitle: 'إدارة مواعيد الجلسات والتقييمات',
    cal_new_btn: 'موعد جديد',
    cal_nav_title: 'تصفح التقويم',
    cal_summary_title: 'ملخص المواعيد',
    cal_completed: 'جلسات مكتملة',
    cal_pending: 'بانتظار الحضور',
    cal_cancelled: 'مواعيد ملغاة',
    cal_today_appointments: 'مواعيد يوم:',
    cal_unknown_patient: 'مريض غير معروف',
    cal_type_assessment: 'جلسة تقييم',
    cal_type_followup: 'جلسة متابعة',
    cal_type_therapy: 'جلسة علاجية',
    cal_status_done: 'تمت',
    cal_status_upcoming: 'قادم',
    cal_no_appointments: 'لا توجد مواعيد لهذا اليوم',
    cal_start_adding: 'يمكنك البدء بإضافة مواعيد جديدة لجلساتك وتقييماتك.',
    cal_modal_title: 'حجز موعد جديد',
    cal_label_patient: 'المريض',
    cal_label_date: 'التاريخ',
    cal_label_time: 'الوقت',
    cal_label_notes: 'ملاحظات (اختياري)',
    cal_btn_confirm: 'تأكيد الحجز',
    cal_days: ['ح', 'ن', 'ث', 'ر', 'خ', 'ج', 'س'],
    // Billing
    bill_title: 'الاشتراكات والترقيات',
    bill_subtitle: 'انطلق بعيادتك نحو آفاق جديدة من الاحترافية والذكاء',
    bill_current_balance: 'رصيدك المتاح حالياً',
    bill_reports: 'تقرير',
    bill_device_id: 'Device Hardware ID',
    bill_activation_title: 'تفعيل كود الاشتراك',
    bill_btn_activate: 'تفعيل الآن',
    bill_support_title: 'للمساعدة والدعم',
    bill_support_sub: 'Customer Success Hub',
    bill_whatsapp_msg: 'تواصل مباشر عبر الواتساب',
    bill_whatsapp_btn: 'ابدأ المحادثة',
    bill_packages_title: 'باقات التقارير الذكية',
    bill_clinical_report: 'تقرير إكلينيكي',
    bill_btn_order: 'اطلب الباقة الآن',
    bill_msg_success: 'تم التفعيل! أضيف +{amount} تقرير لرصيدك.',
    bill_msg_error: 'كود التفعيل غير صحيح.',
    bill_msg_used: 'تم استخدام هذا الكود مسبقاً.',
    // Settings
    set_title: 'إعدادات النظام',
    set_subtitle: 'تحكم في هويتك، أمانك، وتجربتك داخل PsyReports Pro',
    set_nav_profile: 'الملف الشخصي',
    set_nav_security: 'الأمان والتراخيص',
    set_nav_pref: 'التفضيلات والمظهر',
    set_nav_ai: 'الذكاء الاصطناعي',
    set_nav_system: 'البيانات والنسخ',
    set_change_photo: 'تغيير الصورة',
    set_specialist_name: 'اسم الأخصائي',
    set_clinic_name: 'اسم العيادة / المركز',
    set_theme_title: 'نمط عرض النظام',
    set_theme_light: 'الوضع النهاري',
    set_theme_dark: 'الوضع الليلي',
    set_header_title: 'ترويسة التقارير (Header)',
    set_header_desc: 'إظهار شعار العيادة واسم الأخصائي في أعلى التقرير',
    set_ai_title: 'محرك الذكاء الاصطناعي (Gemini AI)',
    set_ai_desc: 'تفعيل هذا الخيار يسمح للبرنامج باستخدام الذكاء الاصطناعي لتحليل درجات الاختبارات واقتراح التفسيرات الإكلينيكية ودمج بيانات المريض التاريخية تلقائياً.',
    set_ai_toggle: 'تفعيل تحليل الحالة الذكي',
    set_backup_title: 'نسخة احتياطية',
    set_backup_desc: 'قم بتصدير كافة بيانات المرضى والأرصدة في ملف مشفر لضمان الأمان.',
    set_backup_btn: 'تحميل ملف النسخة',
    set_restore_title: 'استعادة البيانات',
    set_restore_desc: 'اختر ملف نسخة احتياطية سابقة (بصيغة .psy) لاستعادة البيانات.',
    set_restore_btn: 'اختر ملف الاستعادة'
  },
  en: {
    dashboard: 'Dashboard',
    patients: 'Clinical Registry',
    intake: 'Clinical Intake',
    observation: 'Behavioral MSE',
    assessments: 'Psychometrics',
    dsm: 'DSM-5 Diagnostic Engine',
    recommendations: 'Clinical Interventions',
    reports: 'Report Studio',
    final_report: 'Final Clinical Synthesis',
    calendar: 'Clinical Schedule',
    billing: 'Credits & Billing',
    settings: 'System Configuration',
    sessions: 'Session Reports', // Added
    active_patients: 'Active Cases',
    issued_reports: 'Reports Generated',
    credits: 'Available Credits',
    alerts: 'Clinical Alerts',
    lang_switch: 'الواجهة العربية',
    save: 'Save Changes',
    next: 'Next Section',
    back: 'Previous',
    finish: 'Finish & Finalize',
    select_patient: '-- Select Patient Record --',
    clinical_session_active: 'Clinical Session Active',
    chief_complaint: 'Chief Complaint',
    history_presenting_illness: 'History of Presenting Illness (HPI)',
    symptom_phenomenology: 'Symptom Phenomenology Matrix',
    past_medical_history: 'Past Psychiatric/Medical History',
    family_genetic_history: 'Family & Genetic History',
    developmental_history: 'Developmental Milestones',
    occupational_functioning: 'Global Functional Status',
    clinical_formulation: 'Diagnostic Formulation & Dx',
    mental_status_exam: 'Mental Status Examination (MSE)',
    informant: 'Informant / Source',
    nature_presentation: 'Nature of Presentation',
    onset: 'Nature of Onset',
    course: 'Clinical Course',
    mood_symptoms: 'Affective Symptoms',
    cognitive_symptoms: 'Cognitive Deficits',
    psychotic_symptoms: 'Psychotic Features',
    social_history: 'Social History & Stability',
    edu_occupational: 'Edu/Occupational Performance',
    provisional_dx: 'Provisional Diagnosis',
    plan: 'Treatment & Intervention Plan',
    clinical_notes: 'Clinical Remarks',
    reset_analysis: 'Reset Analysis',
    met: 'Criteria Met',
    not_met: 'Under Evaluation',
    psychometrics_unit: 'Psychometric Unit',
    manual_entry: 'Scoring Interface',
    select_test: 'Select Assessment',
    score_val: 'Value',
    score_class: 'Classification',
    ai_analysis: 'AI Synthesis',
    generate_ai: 'Generate Analysis',
    finalize_assessment: 'Finalize Assessment',
    specialist_notes: 'Specialist Notes',
    enter_observations: 'Enter clinical observations...',
    // Session Recorder
    sr_title: 'Therapeutic Session Register',
    sr_subtitle: 'Clinical Documentation (SOAP Notes)',
    sr_new_note: 'New Session',
    sr_history: 'Session History',
    sr_date: 'Session Date',
    sr_duration: 'Duration (min)',
    sr_session_num: 'Session #',
    sr_subjective: 'Subjective (S)',
    sr_subjective_ph: 'Patient quotes, current complaint, updates since last session...',
    sr_objective: 'Objective (O)',
    sr_objective_ph: 'Appearance, behavior, affect, MSE during session...',
    sr_assessment: 'Assessment (A)',
    sr_assessment_ph: 'Therapist analysis of progress, insight, clinical changes...',
    sr_plan: 'Plan (P)',
    sr_plan_ph: 'Homework, next session focus, scheduling...',
    sr_interventions: 'Interventions Used',
    sr_mood_rating: 'Mood Rating (1-10)',
    sr_risk: 'Risk Assessment',
    sr_risk_low: 'Low',
    sr_risk_med: 'Medium',
    sr_risk_high: 'High',
    sr_save_btn: 'Finalize & Save Note',
    sr_no_history: 'No sessions recorded for this patient.',
    sr_view_details: 'View Details',
    // Report Maker Specific
    rm_title: 'Smart Report Composer',
    rm_subtitle: 'Clinical Report Composer',
    rm_import_btn: 'Auto-Import Data',
    rm_preview_btn: 'Preview & Print',
    rm_select_patient: 'Select Patient File',
    rm_tab_context: 'Context & History',
    rm_tab_behavior: 'Behavioral Obs.',
    rm_tab_tests: 'Test Results',
    rm_tab_diagnosis: 'Diagnostic Formulation',
    rm_tab_plan: 'Recommendations',
    rm_ph_context: 'Enter referral reason, HPI, and past medical history...',
    rm_ph_behavior: 'Describe appearance, contact, mood, and general behavior...',
    rm_ph_tests_interp: 'Enter clinical interpretation here...',
    rm_ph_diagnosis: 'Synthesis: Based on the above, the patient presents with...',
    rm_ph_rec_add: 'Type a new recommendation and press Enter...',
    rm_add_test_btn: 'Add Manual Test',
    rm_no_tests: 'No test results found. Click "Auto-Import" or add manually.',
    rm_no_recs: 'No recommendations added yet.',
    // Report Print View
    print_title: 'Clinical Psychological Report',
    print_subtitle: 'Confidential Clinical Psychological Report',
    print_ref: 'Ref',
    print_date: 'Date',
    print_pt_name: 'Patient Name',
    print_pt_dob: 'Date of Birth',
    print_pt_gender: 'Gender',
    print_pt_ref: 'Referred By',
    print_sec_context: 'Referral Reason & Case History',
    print_sec_behavior: 'Behavioral Observations (MSE)',
    print_sec_tests: 'Psychometric Assessment Results',
    print_sec_diagnosis: 'Clinical Summary & Diagnosis',
    print_sec_plan: 'Recommendations & Plan',
    print_footer_sig: 'Signature',
    print_footer_spec: 'Clinical Psychologist',
    print_footer_stamp: 'Clinic Stamp',
    print_back: 'Back to Editor',
    print_save: 'Save Draft',
    print_action: 'Print / Export PDF',
    // Recommendations Engine
    re_title: 'Intervention Matrix',
    re_subtitle: 'Clinical Intervention Matrix',
    re_add_btn: 'Add New Recommendation',
    re_filter_dx: 'Filter by Diagnosis',
    re_search_ph: 'Search recommendations...',
    re_cat_all: 'All',
    re_cat_school: 'School',
    re_cat_home: 'Home',
    re_selected: 'Recommendations Selected',
    re_copy_bulk: 'Copy Batch',
    re_cancel: 'Deselect',
    re_type_acc: 'Accommodation',
    re_type_mod: 'Modification',
    re_modal_title: 'Add Custom Recommendation',
    re_modal_text: 'Recommendation Text',
    re_modal_cat: 'Category',
    re_modal_type: 'Type',
    re_modal_tags: 'Tags (e.g., ADHD)',
    re_modal_save: 'Save to Bank',
    // Patient Manager
    pm_search_placeholder: 'Search by name or phone number...',
    pm_add_btn: 'Add Patient',
    pm_full_record: 'Full Record',
    pm_edit_title: 'Edit Patient Details',
    pm_new_title: 'Add New Patient',
    pm_label_name: 'Full Name',
    pm_ph_name: 'Enter full name',
    pm_label_dob: 'Date of Birth',
    pm_calc_age: 'Calculated Age',
    pm_label_phone: 'Phone Number',
    pm_label_gender: 'Gender',
    pm_gender_male: 'Male',
    pm_gender_female: 'Female',
    pm_label_notes: 'Additional Notes (Optional)',
    pm_ph_notes: 'Brief clinical history or initial notes...',
    pm_cancel: 'Cancel',
    pm_save: 'Save Data',
    pm_err_required: 'Basic information is required',
    // Final Report Manager
    fr_title: 'Final Report Drafting Engine',
    fr_select_label: 'Select Patient File for Import',
    fr_select_ph: '-- Select Patient for Clinical Review --',
    fr_readiness: 'Data Readiness for Final Report',
    fr_intake: 'Clinical Intake',
    fr_mse: 'Observation (MSE)',
    fr_tests: 'Assessments',
    fr_dx_plan: 'Diagnosis & Recs',
    fr_btn_generate: 'Draft & Preview Comprehensive Report',
    fr_err_missing: 'Cannot generate report without basic Clinical Intake data.',
    fr_optional: 'Optional',
    fr_none: 'None',
    // Final Report Preview
    rp_header_title: 'Export Final Report',
    rp_edit: 'Edit Report',
    rp_save: 'Save Changes',
    rp_print: 'Print Report',
    rp_sec_1: 'First: Case History & Complaint',
    rp_sec_2: 'Second: Psychometric Assessment Results',
    rp_sec_3: 'Third: Final Clinical Diagnosis',
    rp_sec_4: 'Fourth: Intervention Recommendations',
    rp_tbl_domain: 'Domain / Unit',
    rp_tbl_score: 'Score',
    rp_tbl_class: 'Interpretation',
    rp_sig_spec: 'Treating Specialist Signature',
    rp_sig_stamp: 'Official Clinic Stamp',
    rp_add_rec: 'Add Recommendation',
    // Calendar
    cal_title: 'Daily Agenda',
    cal_subtitle: 'Manage sessions and assessments',
    cal_new_btn: 'New Appointment',
    cal_nav_title: 'Calendar Navigation',
    cal_summary_title: 'Appointments Summary',
    cal_completed: 'Completed Sessions',
    cal_pending: 'Pending Attendance',
    cal_cancelled: 'Cancelled',
    cal_today_appointments: 'Appointments for:',
    cal_unknown_patient: 'Unknown Patient',
    cal_type_assessment: 'Assessment Session',
    cal_type_followup: 'Follow-up Session',
    cal_type_therapy: 'Therapy Session',
    cal_status_done: 'Done',
    cal_status_upcoming: 'Upcoming',
    cal_no_appointments: 'No appointments for this day',
    cal_start_adding: 'You can start adding new appointments for your sessions and assessments.',
    cal_modal_title: 'Book New Appointment',
    cal_label_patient: 'Patient',
    cal_label_date: 'Date',
    cal_label_time: 'Time',
    cal_label_notes: 'Notes (Optional)',
    cal_btn_confirm: 'Confirm Booking',
    cal_days: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
    // Billing
    bill_title: 'Subscriptions & Upgrades',
    bill_subtitle: 'Elevate your clinic with professional intelligence',
    bill_current_balance: 'Current Balance',
    bill_reports: 'Reports',
    bill_device_id: 'Device Hardware ID',
    bill_activation_title: 'Activate Subscription Code',
    bill_btn_activate: 'Activate Now',
    bill_support_title: 'Help & Support',
    bill_support_sub: 'Customer Success Hub',
    bill_whatsapp_msg: 'Chat via WhatsApp',
    bill_whatsapp_btn: 'Start Chat',
    bill_packages_title: 'Smart Report Packages',
    bill_clinical_report: 'Clinical Report',
    bill_btn_order: 'Order Package',
    bill_msg_success: 'Activation Successful! +{amount} reports added.',
    bill_msg_error: 'Invalid activation code.',
    bill_msg_used: 'Code already used.',
    // Settings
    set_title: 'System Configuration',
    set_subtitle: 'Control your identity, security, and experience within PsyReports Pro',
    set_nav_profile: 'Profile',
    set_nav_security: 'Security & Licenses',
    set_nav_pref: 'Preferences & Appearance',
    set_nav_ai: 'Artificial Intelligence',
    set_nav_system: 'Data & Backup',
    set_change_photo: 'Change Photo',
    set_specialist_name: 'Specialist Name',
    set_clinic_name: 'Clinic / Center Name',
    set_theme_title: 'System Theme',
    set_theme_light: 'Light Mode',
    set_theme_dark: 'Dark Mode',
    set_header_title: 'Report Header',
    set_header_desc: 'Show clinic logo and specialist name at the top of the report',
    set_ai_title: 'Gemini AI Engine',
    set_ai_desc: 'Enabling this option allows the software to use AI to analyze test scores, suggest clinical interpretations, and automatically integrate historical patient data.',
    set_ai_toggle: 'Enable Smart Case Analysis',
    set_backup_title: 'Backup Data',
    set_backup_desc: 'Export all patient data and credits in an encrypted file to ensure security.',
    set_backup_btn: 'Download Backup File',
    set_restore_title: 'Restore Data',
    set_restore_desc: 'Select a previous backup file (.psy) to restore data.',
    set_restore_btn: 'Select Backup File'
  }
};

export const SCORE_LABELS: Record<string, { ar: string; en: string }> = {
  // IQ
  fsiq: { ar: 'الدرجة الكلية (IQ)', en: 'Full Scale IQ' },
  viq: { ar: 'الذكاء اللفظي', en: 'Verbal IQ' },
  piq: { ar: 'الذكاء الأدائي', en: 'Performance IQ' },
  wm: { ar: 'الذاكرة العاملة', en: 'Working Memory' },
  ps: { ar: 'سرعة المعالجة', en: 'Processing Speed' },
  // CARS
  cars_total: { ar: 'الدرجة الكلية (CARS)', en: 'Total Score' },
  social: { ar: 'التفاعل الاجتماعي', en: 'Social Interaction' },
  emotional: { ar: 'الاستجابة الانفعالية', en: 'Emotional Response' },
  body_use: { ar: 'استخدام الجسم', en: 'Body Use' },
  object_use: { ar: 'استخدام الأشياء', en: 'Object Use' },
  adaptation: { ar: 'التكيف مع التغيير', en: 'Adaptation to Change' },
  visual: { ar: 'الاستجابة البصرية', en: 'Visual Response' },
  auditory: { ar: 'الاستجابة السمعية', en: 'Auditory Response' },
  taste_smell: { ar: 'التذوق والشم واللمس', en: 'Taste, Smell, Touch' },
  fear: { ar: 'الخوف والقلق', en: 'Fear and Anxiety' },
  verbal: { ar: 'التواصل اللفظي', en: 'Verbal Communication' },
  nonverbal: { ar: 'التواصل غير اللفظي', en: 'Non-Verbal Communication' },
  activity_level: { ar: 'مستوى النشاط', en: 'Activity Level' },
  consistency: { ar: 'الثبات الفكري', en: 'Consistency' },
  general_impression: { ar: 'الانطباع العام', en: 'General Impression' },
  // CONNERS
  conners_total: { ar: 'الدرجة الكلية', en: 'Total Score' },
  inattention: { ar: 'نقص الانتباه', en: 'Inattention' },
  hyperactivity: { ar: 'فرط الحركة', en: 'Hyperactivity/Impulsivity' },
  learning_problems: { ar: 'مشاكل التعلم', en: 'Learning Problems' },
  executive_functioning: { ar: 'الوظائف التنفيذية', en: 'Executive Functioning' },
  defiance: { ar: 'التحدي/العدوانية', en: 'Defiance/Aggression' },
  peer_relations: { ar: 'العلاقات مع الرفاق', en: 'Peer Relations' },
  // BDI
  bdi_total: { ar: 'درجة الاكتئاب', en: 'Depression Score' },
  cognitive_affective: { ar: 'الأعراض المعرفية الوجدانية', en: 'Cognitive-Affective' },
  somatic: { ar: 'الأعراض الجسدية', en: 'Somatic Symptoms' },
  // GAD
  gad_total: { ar: 'درجة القلق', en: 'Anxiety Score' },
  worry: { ar: 'القلق والتوتر', en: 'Worry/Tension' },
  physical: { ar: 'الأعراض الجسدية', en: 'Physical Symptoms' },
  // VINELAND
  vineland_total: { ar: 'السلوك التكيفي الكلي', en: 'Adaptive Behavior Composite' },
  communication: { ar: 'التواصل', en: 'Communication' },
  daily_living: { ar: 'مهارات الحياة اليومية', en: 'Daily Living Skills' },
  socialization: { ar: 'التنشئة الاجتماعية', en: 'Socialization' },
  motor_skills: { ar: 'المهارات الحركية', en: 'Motor Skills' },
  // General
  total: { ar: 'الدرجة الكلية', en: 'Total Score' },
  reaction_ms: { ar: 'زمن رد الفعل (مللي ثانية)', en: 'Reaction Time (ms)' },
};

export const ASSESSMENT_CONFIGS: Record<string, { title: { ar: string; en: string }; fields: string[] }> = {
  [AssessmentType.IQ]: {
    title: { ar: 'مقياس ستانفورد بينيه (الصورة الخامسة)', en: 'Stanford-Binet Intelligence Scales (SB5)' },
    fields: ['fsiq', 'viq', 'piq', 'wm', 'ps'],
  },
  [AssessmentType.WISC]: {
    title: { ar: 'مقياس وكسلر لذكاء الأطفال (WISC-V)', en: 'Wechsler Intelligence Scale for Children (WISC-V)' },
    fields: ['fsiq', 'viq', 'piq', 'wm', 'ps'],
  },
  [AssessmentType.AUTISM]: {
    title: { ar: 'مقياس تقييم التوحد (CARS-2)', en: 'Childhood Autism Rating Scale (CARS-2)' },
    fields: ['cars_total', 'social', 'emotional', 'body_use', 'object_use', 'adaptation', 'visual', 'auditory', 'taste_smell', 'fear', 'verbal', 'nonverbal', 'activity_level', 'consistency', 'general_impression'],
  },
  [AssessmentType.CONNERS]: {
    title: { ar: 'مقياس كونرز (النسخة الثالثة)', en: 'Conners 3rd Edition' },
    fields: ['conners_total', 'inattention', 'hyperactivity', 'learning_problems', 'executive_functioning', 'defiance', 'peer_relations'],
  },
  [AssessmentType.DEPRESSION]: {
    title: { ar: 'مقياس بيك للاكتئاب (BDI-II)', en: 'Beck Depression Inventory (BDI-II)' },
    fields: ['bdi_total', 'cognitive_affective', 'somatic'],
  },
  [AssessmentType.ANXIETY]: {
    title: { ar: 'مقياس قلق الأطفال (Spence)', en: 'Spence Children\'s Anxiety Scale' },
    fields: ['gad_total', 'worry', 'physical'],
  },
  [AssessmentType.VINELAND]: {
    title: { ar: 'مقياس فاينلاند للسلوك التكيفي (Vineland-3)', en: 'Vineland Adaptive Behavior Scales (Vineland-3)' },
    fields: ['vineland_total', 'communication', 'daily_living', 'socialization', 'motor_skills'],
  },
  [AssessmentType.GARS]: { title: { ar: 'مقياس جيليام (GARS-3)', en: 'GARS-3' }, fields: ['total'] },
  [AssessmentType.SRS]: { title: { ar: 'مقياس الاستجابة الاجتماعية (SRS-2)', en: 'SRS-2' }, fields: ['total'] },
  [AssessmentType.VANDERBILT]: { title: { ar: 'مقياس فاندربيلت', en: 'Vanderbilt Assessment' }, fields: ['total'] },
  [AssessmentType.LANGUAGE]: { title: { ar: 'مقياس اللغة', en: 'Language Assessment' }, fields: ['total'] },
  [AssessmentType.SUMMARY]: { title: { ar: 'ملخص', en: 'Summary' }, fields: ['total'] },
  [AssessmentType.FOCUS_GAME]: { title: { ar: 'لعبة التركيز', en: 'Focus Game' }, fields: ['reaction_ms'] },
};

export const PACKAGES = [
  {
    id: 'pkg_10',
    name: { ar: 'باقة الانطلاق', en: 'Starter Pack' },
    count: 10,
    price: { ar: '100 ج.م', en: '100 EGP' },
    discount: { ar: 'تجربة مثالية', en: 'Good for trial' },
  },
  {
    id: 'pkg_20',
    name: { ar: 'باقة 20 تقرير', en: 'Basic Pack' },
    count: 20,
    price: { ar: '180 ج.م', en: '180 EGP' },
    discount: { ar: 'توفير 10%', en: 'Save 10%' },
  },
  {
    id: 'pkg_50',
    name: { ar: 'باقة 50 تقرير', en: 'Standard Pack' },
    count: 50,
    price: { ar: '480 ج.م', en: '480 EGP' },
    discount: { ar: 'توفير 20%', en: 'Save 20%' },
  },
  {
    id: 'pkg_100',
    name: { ar: 'باقة 100 تقرير', en: 'Premium Pack' },
    count: 100,
    price: { ar: '875 ج.م', en: '875 EGP' },
    discount: { ar: 'قيمة ممتازة', en: 'Great Value' },
  },
  {
    id: 'pkg_200',
    name: { ar: 'باقة 200 تقرير', en: 'Professional Pack' },
    count: 200,
    price: { ar: '1775 ج.م', en: '1775 EGP' },
    discount: { ar: 'للعيادات', en: 'For Clinics' },
  },
  {
    id: 'pkg_inf',
    name: { ar: 'باقة غير محدودة', en: 'Unlimited Access' },
    count: Infinity,
    price: { ar: '6500 ج.م', en: '6500 EGP' },
    discount: { ar: 'وصول كامل مدى الحياة', en: 'Lifetime Access' },
  },
];

export const DSM5_DATA: Record<string, { criteria: any[] }> = {
  AUTISM: {
    criteria: [
      {
        id: 'A',
        title: { ar: 'أ. العجز المستمر في التواصل والتفاعل الاجتماعي', en: 'A. Persistent deficits in social communication and social interaction' },
        description: { ar: 'يجب توفر الأعراض الثلاثة التالية:', en: 'Must have all 3 of the following:' },
        minRequired: 3,
        symptoms: [
          { id: 'A1', text: { ar: 'عجز في التبادل الاجتماعي والعاطفي (مثل الفشل في المحادثة المتبادلة)', en: 'Deficits in social-emotional reciprocity (e.g., failure of back-and-forth conversation)' } },
          { id: 'A2', text: { ar: 'عجز في السلوكيات غير اللفظية (مثل التواصل البصري ولغة الجسد)', en: 'Deficits in nonverbal communicative behaviors (e.g., eye contact, body language)' } },
          { id: 'A3', text: { ar: 'عجز في تطوير العلاقات والحفاظ عليها وفهمها', en: 'Deficits in developing, maintaining, and understanding relationships' } },
        ],
      },
      {
        id: 'B',
        title: { ar: 'ب. أنماط سلوك أو اهتمامات أو أنشطة مقيدة ومتكررة', en: 'B. Restricted, repetitive patterns of behavior, interests, or activities' },
        description: { ar: 'يجب توفر عرضين على الأقل مما يلي:', en: 'Must have at least 2 of the following:' },
        minRequired: 2,
        symptoms: [
          { id: 'B1', text: { ar: 'حركات نمطية أو متكررة (مثل رفرفة اليدين)', en: 'Stereotyped or repetitive motor movements (e.g., hand flapping)' } },
          { id: 'B2', text: { ar: 'الإصرار على الروتين أو مقاومة التغيير', en: 'Insistence on sameness, inflexible adherence to routines' } },
          { id: 'B3', text: { ar: 'اهتمامات مقيدة وثابتة للغاية', en: 'Highly restricted, fixated interests' } },
          { id: 'B4', text: { ar: 'فرط أو نقص الاستجابة للمدخلات الحسية', en: 'Hyper- or hyporeactivity to sensory input' } },
        ],
      },
    ],
  },
  ADHD: {
    criteria: [
       {
        id: 'A1',
        title: { ar: 'أ1. نقص الانتباه', en: 'A1. Inattention' },
        description: { ar: '6 أعراض أو أكثر (5 للكبار) لمدة 6 أشهر', en: '6 or more symptoms (5 for adults) for 6 months' },
        minRequired: 6,
        symptoms: [
          { id: 'a1', text: { ar: 'يفشل في الانتباه للتفاصيل أو يرتكب أخطاء', en: 'Fails to give close attention to details' } },
          { id: 'a2', text: { ar: 'صعوبة في الحفاظ على الانتباه في المهام', en: 'Difficulty sustaining attention in tasks' } },
          { id: 'a3', text: { ar: 'لا يبدو أنه يستمع عند التحدث إليه مباشرة', en: 'Does not seem to listen when spoken to directly' } },
          { id: 'a4', text: { ar: 'لا يتبع التعليمات ويفشل في إنهاء الواجبات', en: 'Does not follow instructions and fails to finish duties' } },
          { id: 'a5', text: { ar: 'صعوبة في تنظيم المهام والأنشطة', en: 'Difficulty organizing tasks and activities' } },
          { id: 'a6', text: { ar: 'يتجنب المهام التي تتطلب جهداً عقلياً مستمراً', en: 'Avoids tasks requiring sustained mental effort' } },
          { id: 'a7', text: { ar: 'يفقد الأشياء الضرورية للمهام', en: 'Loses things necessary for tasks' } },
          { id: 'a8', text: { ar: 'سهل التشتت بالمثيرات الخارجية', en: 'Easily distracted by extraneous stimuli' } },
          { id: 'a9', text: { ar: 'كثير النسيان في الأنشطة اليومية', en: 'Forgetful in daily activities' } },
        ]
       }
    ]
  },
  ANXIETY: { criteria: [] },
  DEPRESSION: { criteria: [] },
  BIPOLAR: { criteria: [] },
  SCHIZOPHRENIA: { criteria: [] },
  OCD: { criteria: [] },
  PTSD: { criteria: [] },
  ODD: { criteria: [] },
  CONDUCT: { criteria: [] },
  SOCIAL_ANXIETY: { criteria: [] }
};

export const RECOMMENDATIONS_BANK: Recommendation[] = [
  {
    id: 'rec1',
    text: 'توفير وقت إضافي للاختبارات (50% زيادة) لتقليل قلق الأداء.',
    textEn: 'Provide extended time for tests (50% extra) to reduce performance anxiety.',
    category: 'School',
    type: 'Accommodation',
    tags: ['Anxiety', 'ADHD', 'Learning'],
  },
  {
    id: 'rec2',
    text: 'تقسيم المهام الكبيرة إلى خطوات صغيرة قابلة للإنجاز مع مكافآت فورية.',
    textEn: 'Break down large tasks into smaller, manageable steps with immediate rewards.',
    category: 'Home',
    type: 'Modification',
    tags: ['ADHD', 'Executive Function'],
  },
  {
    id: 'rec3',
    text: 'استخدام جداول بصرية لتنظيم الروتين اليومي.',
    textEn: 'Use visual schedules to organize daily routines.',
    category: 'Home',
    type: 'Accommodation',
    tags: ['Autism', 'ADHD'],
  },
  {
    id: 'rec4',
    text: 'الجلوس في الصف الأمامي بعيداً عن المشتتات (النوافذ، الأبواب).',
    textEn: 'Preferential seating in the front row, away from distractions (windows, doors).',
    category: 'School',
    type: 'Accommodation',
    tags: ['ADHD', 'Attention'],
  },
];
